services:
  - type: web
    name: mind2market-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.enableCORS false"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set it manually via the Render dashboard for security
